package config

import (
	"fmt"
	"strings"
)

// BuildSeedSQL renders the reference data (crafts, product categories, and their
// links) as an idempotent SQL migration body. It reuses the same seed slices and
// keyword normalization as the rest of the app, so the generated SQL cannot drift
// from the in-code source of truth. See cmd/seedgen for the CLI wrapper.
func BuildSeedSQL() string {
	var b strings.Builder
	b.WriteString("-- Reference data: crafts, product categories, and their links.\n")
	b.WriteString("-- Generated by `go run ./cmd/seedgen`. Do not edit by hand — change the\n")
	b.WriteString("-- seed slices in config/seed.go and regenerate a new versioned migration.\n\n")

	emitSeedUpsert(&b, "crafts", craftSeed)
	emitSeedUpsert(&b, "product_categories", productCategorySeed)

	// Remove stale reference rows that are no longer in the seed so the code
	// stays the single source of truth. Runs after the upserts (which guarantee
	// the current rows exist) and before the link rebuild below. Deleting a
	// craft/category cascades its craft_product_categories links; the link table
	// is rebuilt from scratch immediately afterwards. A category still referenced
	// by a product will make this fail loudly (products.category_id is RESTRICT),
	// which is intentional — resolve those products before dropping the category.
	emitSeedCleanup(&b, "product_categories", productCategorySeed)
	emitSeedCleanup(&b, "crafts", craftSeed)

	b.WriteString("-- Rebuild the craft <-> category links from the current mapping so the\n")
	b.WriteString("-- code stays the single source of truth (stale links are removed).\n")
	b.WriteString("DELETE FROM \"craft_product_categories\";\n")
	b.WriteString("INSERT INTO \"craft_product_categories\" (\"craft_id\", \"category_id\")\n")
	b.WriteString("SELECT c.id, pc.id FROM \"crafts\" c JOIN \"product_categories\" pc ON TRUE\n")
	b.WriteString("WHERE (c.name, pc.name) IN (\n")

	pairs := make([]string, 0)
	// Deterministic order: crafts in seed order, categories as listed.
	for _, craft := range craftSeed {
		cats, ok := craftCategoryLinks[craft.Name]
		if !ok {
			continue
		}
		for _, cat := range cats {
			pairs = append(pairs, fmt.Sprintf("  (%s, %s)", sqlString(craft.Name), sqlString(cat)))
		}
	}
	b.WriteString(strings.Join(pairs, ",\n"))
	b.WriteString("\n);\n")

	return b.String()
}

func emitSeedUpsert(b *strings.Builder, table string, items []seedItem) {
	fmt.Fprintf(b, "INSERT INTO %q (\"name\", \"keywords\", \"search_keywords\") VALUES\n", table)
	for i, item := range items {
		sep := ","
		if i == len(items)-1 {
			sep = ""
		}
		fmt.Fprintf(b, "  (%s, %s, %s)%s\n",
			sqlString(item.Name),
			sqlTextArray(item.Keywords),
			sqlTextArray(buildSearchKeywords(item.Name, item.Keywords)),
			sep,
		)
	}
	b.WriteString("ON CONFLICT (\"name\") DO UPDATE SET\n")
	b.WriteString("  \"keywords\" = EXCLUDED.\"keywords\",\n")
	b.WriteString("  \"search_keywords\" = EXCLUDED.\"search_keywords\";\n\n")
}

func emitSeedCleanup(b *strings.Builder, table string, items []seedItem) {
	names := make([]string, len(items))
	for i, item := range items {
		names[i] = sqlString(item.Name)
	}
	fmt.Fprintf(b, "-- Remove stale %s rows no longer present in the seed.\n", table)
	fmt.Fprintf(b, "DELETE FROM %q WHERE \"name\" NOT IN (\n  %s\n);\n\n", table, strings.Join(names, ",\n  "))
}

func sqlString(s string) string {
	return "'" + strings.ReplaceAll(s, "'", "''") + "'"
}

func sqlTextArray(values []string) string {
	quoted := make([]string, len(values))
	for i, v := range values {
		quoted[i] = sqlString(v)
	}
	return "ARRAY[" + strings.Join(quoted, ",") + "]::text[]"
}
